language: ruby
rvm: 1.8.7
script: "rake spec"
branches:
  only:
    - master
notifications:
  email:
    - github@razorsedge.org
env:
  - PUPPET_VERSION=2.6.4
  - PUPPET_VERSION=2.6.9
  - PUPPET_VERSION=2.6.16
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=2.7.12
  - PUPPET_VERSION=2.7.18
